### ISSUE TITLE
P0: npm install -g fails on npm 10/11 because preinstall calls scripts/ that the tarball does not ship

### ISSUE THREAD

**Issue by RonenMars** [RonenMars/threadbase-streamer#812]
`npm install -g @threadbase-sh/streamer` fails on npm 10 and 11, which is the npm bundled with the Node majors most users run.
Node 24.15.0 bundles npm 11.12.1.

`package.json` declares `"files": ["dist"]`, so the published tarball contains no `package/scripts/` directory at all.
It also declares `"preinstall": "node scripts/check-node-version.mjs --warn && node scripts/check-native-abi.mjs --warn"`.
npm 10 and 11 run a dependency's install scripts by default, so the preinstall executes, cannot resolve the file, exits 1, and npm rolls the whole install back.

npm 12 happens to survive this because it blocks dependency install scripts by default — the preinstall never runs.
That is luck, not a fix: it also means the guard those two scripts exist to provide has never run for any published install on any npm major.

This is not Windows-specific.
`preinstall` and the missing `scripts/` directory are both platform-independent, so macOS and Linux global installs should fail identically; I verified on Windows only.

Introduced in #176 (2026-07-05), which added the `preinstall` without adding `scripts/` to `files`.
Every release published since then carries it, `1.85.0` included.

Two candidate fixes, not yet evaluated against each other:
- add `scripts/` (or just the two `.mjs` files) to the `files` array so the tarball carries what `preinstall` calls
- drop `preinstall` from the published manifest, since an ABI guard against a prebuilt-only install has little to check

## Verified state

Windows 10, Node 24.15.0, checked 2026-09-07.
Installed into an isolated prefix (`--prefix C:\tmp\...`) rather than the real global bin, because the package's `bin` claims `tb-streamer` and `threadbase-streamer` and would overwrite a `scripts/deploy.sh` install's shims.

npm 11.12.1, `npx -y npm@11 install -g @threadbase-sh/streamer --prefix <tmp>`:

```
npm error code 1
npm error path C:\tmp\tb529b\node_modules\@threadbase-sh\streamer
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node scripts/check-node-version.mjs --warn && node scripts/check-native-abi.mjs --warn
npm error Error: Cannot find module 'C:\tmp\tb529b\node_modules\@threadbase-sh\streamer\scripts\check-node-version.mjs'
npm error   code: 'MODULE_NOT_FOUND',
```

npm 12.0.2, same command: `added 139 packages in 17s`, with the preinstall reported as blocked rather than run:

```
npm warn install-scripts 3 packages had install scripts blocked because they are not covered by allowScripts:
npm warn install-scripts   @threadbase-sh/streamer@1.85.0 (preinstall: node scripts/check-node-version.mjs --warn && node scripts/check-native-abi.mjs --warn; postinstall: ...)
```

Tarball contents confirm the mismatch:

```
$ npm pack @threadbase-sh/streamer@1.85.0
$ tar -tzf threadbase-sh-streamer-1.85.0.tgz | grep -c '^package/scripts/'
0
$ npm view @threadbase-sh/streamer@1.85.0 files
[ "dist" ]
$ npm view @threadbase-sh/streamer@1.85.0 scripts.preinstall
node scripts/check-node-version.mjs --warn && node scripts/check-native-abi.mjs --warn
```

Found while verifying #529, whose own question resolved cleanly and separately.

**Comment by RonenMars** [comment]
Fixed by #814, released in `1.86.1`.

`package.json` now lists the two guard scripts in `files`, so the tarball carries what `preinstall` invokes.
`__tests__/package-manifest.test.ts` locks it in by asserting that every `scripts/…` path referenced by a consumer-run hook (`preinstall`, `install`, `postinstall`) both exists in the repo and is covered by `files` — it targets the class rather than this one instance, so a new hook reaching into `scripts/` fails the suite.

Shipping the scripts was chosen over dropping the `preinstall`, the other option listed above.
Both scripts degrade correctly in a consumer install rather than misfiring: `--warn` makes each exit 0 unconditionally, `check-node-version.mjs` reads `engines.node` from the published `package.json` and falls back to the range's major when `.nvmrc` is absent from the tarball, and `check-native-abi.mjs` exits early because a prebuilt-only v13 install has no `build/Release`.
Dropping the hook would have removed the ABI guard from the dev checkout, where it does real work.

## Verified state

Windows 10, Node 24.15.0, checked 2026-09-07 against the published `1.86.1`, not a local build.

The tarball now carries the files:

```
$ npm pack @threadbase-sh/streamer@latest
$ tar -tzf threadbase-sh-streamer-1.86.1.tgz | grep '^package/scripts/'
package/scripts/check-native-abi.mjs
package/scripts/check-node-version.mjs
```

A global install under npm 11.18.0 with the install scripts allowed to run — the exact case that failed:

```
$ npx -y npm@11 install -g @threadbase-sh/streamer@1.86.1 --prefix <tmp> --allow-scripts=@threadbase-sh/streamer
added 139 packages in 27s
$ node <tmp>/node_modules/@threadbase-sh/streamer/dist/cli.cjs --version
1.86.1+source
```

The same command against `1.85.0` still ends in `Cannot find module '…\scripts\check-node-version.mjs'`, so anyone pinned below `1.86.1` is unaffected by the fix and needs to upgrade.

## Left open deliberately

Installing from a local tarball path, npm also lists `prepare: patch-package && git config core.hooksPath scripts/git-hooks` among this package's scripts.
`patch-package` is a devDependency and `patches/` is not published, so that would fail if npm ever ran it for a consumer.
Registry installs did not list it, so it appears to be local-path-install behaviour rather than something end users hit.
Not folded into #814; worth its own issue if anyone reproduces it from a registry install.
